name: Homes
version: ${version}
main: io.github.sxnsh1ness.homes.HomesPlugin
api-version: '1.13'
author: Sxnsh1ne
depend: [LuckPerms]
commands:
  home:
    description: Телепортироваться на точку дома
    usage: /home <название>
  sethome:
    description: Создать точку дома
    usage: /sethome <название>
  deletehome:
    description: Удалить точку дома
    usage: /<command> <название>
    aliases: [delhome]
  renamehome:
    description: Переименовать точку дома
    usage: /renamehome <старое_название> <новое_название>
  homes:
    description: Посмотреть список ваших домов
    usage: /homes
permissions:
  homes.use:
    description: Позволяет использовать все команды плагина
    default: true
  homes.admin:
    description: Административные права
    default: op
